name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.2.8
  hooks_riverpod: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
