services:
  db:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  api:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${USERNAME}
      DB_PASSWORD: ${USERPASS}
      DB_NAME: ${DATABASE}
    ports:
      - "8080:8080"
    working_dir: /app
    tty: true
    restart: always

volumes:
  db_data:
    driver: local
